"""create learning tables

Revision ID: 0581b5617aea
Revises: 0001_create_users_table
Create Date: 2026-04-03 08:08:25.720003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0581b5617aea'
down_revision: Union[str, None] = '0001_create_users_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('LESSON', 'STREAK', 'CHALLENGE', 'REVIVE_LIFE', 'HINT', name='coinreason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount <> 0', name='ck_coin_transactions_amount_non_zero'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_transactions_user_id'), 'coin_transactions', ['user_id'], unique=False)
    op.create_table('concept_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('error_type', sa.Enum('FACTUAL', 'CONCEPTUAL', 'CONTEXTUAL', name='errortype'), nullable=False),
    sa.Column('weakness_score', sa.Float(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('avg_response_time_ms >= 0', name='ck_concept_gaps_avg_response_time_non_negative'),
    sa.CheckConstraint('weakness_score <= 1.0', name='ck_concept_gaps_weakness_max'),
    sa.CheckConstraint('weakness_score >= 0.0', name='ck_concept_gaps_weakness_min'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_gaps_topic_id', 'concept_gaps', ['topic_id'], unique=False)
    op.create_index(op.f('ix_concept_gaps_user_id'), 'concept_gaps', ['user_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('xp_gained', sa.Integer(), nullable=False),
    sa.Column('coins_gained', sa.Integer(), nullable=False),
    sa.Column('lives_lost', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('coins_gained >= 0', name='ck_learning_sessions_coins_gained_non_negative'),
    sa.CheckConstraint('lives_lost >= 0', name='ck_learning_sessions_lives_lost_non_negative'),
    sa.CheckConstraint('xp_gained >= 0', name='ck_learning_sessions_xp_gained_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_sessions_topic_id', 'learning_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('topic_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_percentage <= 100.0', name='ck_topic_progress_completion_max'),
    sa.CheckConstraint('completion_percentage >= 0.0', name='ck_topic_progress_completion_min'),
    sa.CheckConstraint('xp_earned >= 0', name='ck_topic_progress_xp_earned_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_topic_progress_user_topic')
    )
    op.create_index('ix_topic_progress_topic_id', 'topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_user_id'), 'topic_progress', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_name', name='uq_user_badges_user_badge')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('lives', sa.Integer(), nullable=False),
    sa.Column('lives_refill_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_day', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coins >= 0', name='ck_user_progress_coins_non_negative'),
    sa.CheckConstraint('level >= 1', name='ck_user_progress_level_min_one'),
    sa.CheckConstraint('lives >= 0', name='ck_user_progress_lives_non_negative'),
    sa.CheckConstraint('longest_streak >= 0', name='ck_user_progress_longest_streak_non_negative'),
    sa.CheckConstraint('streak_day >= 0', name='ck_user_progress_streak_day_non_negative'),
    sa.CheckConstraint('xp_total >= 0', name='ck_user_progress_xp_total_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_topic_progress_user_id'), table_name='topic_progress')
    op.drop_index('ix_topic_progress_topic_id', table_name='topic_progress')
    op.drop_table('topic_progress')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index('ix_learning_sessions_topic_id', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_concept_gaps_user_id'), table_name='concept_gaps')
    op.drop_index('ix_concept_gaps_topic_id', table_name='concept_gaps')
    op.drop_table('concept_gaps')
    op.drop_index(op.f('ix_coin_transactions_user_id'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    # ### end Alembic commands ###
