"""create content tables

Revision ID: 23556878353a
Revises: 0003_create_learning_sync_events
Create Date: 2026-04-19 23:53:18.471450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '23556878353a'
down_revision: Union[str, None] = '0003_create_learning_sync_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('era_start_year', sa.Integer(), nullable=True),
    sa.Column('era_end_year', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('difficulty_hint', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('era_start_year IS NULL OR era_end_year IS NULL OR era_start_year <= era_end_year', name='ck_historical_events_era_year_range'),
    sa.CheckConstraint('version >= 1', name='ck_historical_events_version_min_one'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_events_year', 'historical_events', ['year'], unique=False)
    op.create_table('historical_figures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('difficulty_hint', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('birth_year IS NULL OR death_year IS NULL OR birth_year <= death_year', name='ck_historical_figures_lifespan_range'),
    sa.CheckConstraint('version >= 1', name='ck_historical_figures_version_min_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('historical_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"order" >= 0', name='ck_historical_periods_order_non_negative'),
    sa.CheckConstraint('start_year IS NULL OR end_year IS NULL OR start_year <= end_year', name='ck_historical_periods_year_range'),
    sa.CheckConstraint('version >= 1', name='ck_historical_periods_version_min_one'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_historical_periods_order', 'historical_periods', ['order'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('difficulty_hint', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"order" >= 0', name='ck_topics_order_non_negative'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 10', name='ck_topics_difficulty_range'),
    sa.CheckConstraint('version >= 1', name='ck_topics_version_min_one'),
    sa.CheckConstraint('xp_reward >= 0', name='ck_topics_xp_reward_non_negative'),
    sa.ForeignKeyConstraint(['period_id'], ['historical_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'name', name='uq_topics_period_name')
    )
    op.create_index('ix_topics_order', 'topics', ['order'], unique=False)
    op.create_index('ix_topics_period_id', 'topics', ['period_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('coin_reward', sa.Integer(), nullable=False),
    sa.Column('required_score', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coin_reward >= 0', name='ck_challenges_coin_reward_non_negative'),
    sa.CheckConstraint('required_score >= 0 AND required_score <= 100', name='ck_challenges_required_score_range'),
    sa.CheckConstraint('version >= 1', name='ck_challenges_version_min_one'),
    sa.CheckConstraint('xp_reward >= 0', name='ck_challenges_xp_reward_non_negative'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'title', name='uq_challenges_topic_title')
    )
    op.create_index('ix_challenges_topic_id', 'challenges', ['topic_id'], unique=False)
    op.create_table('topic_event',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['historical_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'event_id')
    )
    op.create_table('topic_figure',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('figure_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['historical_figures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'figure_id')
    )
    op.drop_constraint('learning_sync_events_client_session_id_key', 'learning_sync_events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('learning_sync_events_client_session_id_key', 'learning_sync_events', ['client_session_id'])
    op.drop_table('topic_figure')
    op.drop_table('topic_event')
    op.drop_index('ix_challenges_topic_id', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_topics_period_id', table_name='topics')
    op.drop_index('ix_topics_order', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_historical_periods_order', table_name='historical_periods')
    op.drop_table('historical_periods')
    op.drop_table('historical_figures')
    op.drop_index('ix_historical_events_year', table_name='historical_events')
    op.drop_table('historical_events')
    # ### end Alembic commands ###
