"""add fk topic_id to learning tables

Revision ID: c1b9d88b5614
Revises: 23556878353a
Create Date: 2026-04-19 23:54:43.515918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c1b9d88b5614'
down_revision: Union[str, None] = '23556878353a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Archive orphan rows before cleanup to keep migration traceability.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS migration_orphan_learning_sync_events (
            archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            migration_revision TEXT NOT NULL,
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            client_session_id UUID NOT NULL,
            topic_id UUID NOT NULL,
            learning_session_id UUID NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO migration_orphan_learning_sync_events (
            migration_revision,
            id,
            user_id,
            client_session_id,
            topic_id,
            learning_session_id,
            processed_at
        )
        SELECT
            'c1b9d88b5614',
            lse.id,
            lse.user_id,
            lse.client_session_id,
            lse.topic_id,
            lse.learning_session_id,
            lse.processed_at
        FROM learning_sync_events lse
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = lse.topic_id
        )
        """
    )
    op.execute(
        """
        DELETE FROM learning_sync_events lse
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = lse.topic_id
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS migration_orphan_concept_gaps (
            archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            migration_revision TEXT NOT NULL,
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            topic_id UUID NOT NULL,
            concept VARCHAR NOT NULL,
            error_type errortype NOT NULL,
            weakness_score DOUBLE PRECISION NOT NULL,
            avg_response_time_ms INTEGER,
            detected_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        """
        INSERT INTO migration_orphan_concept_gaps (
            migration_revision,
            id,
            user_id,
            topic_id,
            concept,
            error_type,
            weakness_score,
            avg_response_time_ms,
            detected_at
        )
        SELECT
            'c1b9d88b5614',
            cg.id,
            cg.user_id,
            cg.topic_id,
            cg.concept,
            cg.error_type,
            cg.weakness_score,
            cg.avg_response_time_ms,
            cg.detected_at
        FROM concept_gaps cg
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = cg.topic_id
        )
        """
    )
    op.execute(
        """
        DELETE FROM concept_gaps cg
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = cg.topic_id
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS migration_orphan_learning_sessions (
            archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            migration_revision TEXT NOT NULL,
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            topic_id UUID NOT NULL,
            xp_gained INTEGER NOT NULL,
            coins_gained INTEGER NOT NULL,
            lives_lost INTEGER NOT NULL,
            completed BOOLEAN NOT NULL,
            started_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        """
        INSERT INTO migration_orphan_learning_sessions (
            migration_revision,
            id,
            user_id,
            topic_id,
            xp_gained,
            coins_gained,
            lives_lost,
            completed,
            started_at,
            finished_at
        )
        SELECT
            'c1b9d88b5614',
            ls.id,
            ls.user_id,
            ls.topic_id,
            ls.xp_gained,
            ls.coins_gained,
            ls.lives_lost,
            ls.completed,
            ls.started_at,
            ls.finished_at
        FROM learning_sessions ls
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = ls.topic_id
        )
        """
    )
    op.execute(
        """
        DELETE FROM learning_sessions ls
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = ls.topic_id
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS migration_orphan_topic_progress (
            archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            migration_revision TEXT NOT NULL,
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            topic_id UUID NOT NULL,
            completion_percentage DOUBLE PRECISION NOT NULL,
            xp_earned INTEGER NOT NULL,
            last_studied_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO migration_orphan_topic_progress (
            migration_revision,
            id,
            user_id,
            topic_id,
            completion_percentage,
            xp_earned,
            last_studied_at,
            created_at,
            updated_at
        )
        SELECT
            'c1b9d88b5614',
            tp.id,
            tp.user_id,
            tp.topic_id,
            tp.completion_percentage,
            tp.xp_earned,
            tp.last_studied_at,
            tp.created_at,
            tp.updated_at
        FROM topic_progress tp
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = tp.topic_id
        )
        """
    )
    op.execute(
        """
        DELETE FROM topic_progress tp
        WHERE NOT EXISTS (
            SELECT 1 FROM topics t WHERE t.id = tp.topic_id
        )
        """
    )

    op.create_foreign_key(
        "fk_topic_progress_topic_id_topics",
        "topic_progress",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_learning_sessions_topic_id_topics",
        "learning_sessions",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_concept_gaps_topic_id_topics",
        "concept_gaps",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_learning_sync_events_topic_id_topics",
        "learning_sync_events",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_learning_sync_events_topic_id_topics", "learning_sync_events", type_="foreignkey")
    op.drop_constraint("fk_concept_gaps_topic_id_topics", "concept_gaps", type_="foreignkey")
    op.drop_constraint("fk_learning_sessions_topic_id_topics", "learning_sessions", type_="foreignkey")
    op.drop_constraint("fk_topic_progress_topic_id_topics", "topic_progress", type_="foreignkey")
    # ### end Alembic commands ###
